[2023-11-22T22:41:36.936+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: outcomes_dag.Initialize_wharehouse_schema scheduled__2023-11-15T00:00:00+00:00 [queued]>
[2023-11-22T22:41:36.969+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: outcomes_dag.Initialize_wharehouse_schema scheduled__2023-11-15T00:00:00+00:00 [queued]>
[2023-11-22T22:41:36.970+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-11-22T22:41:37.009+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): Initialize_wharehouse_schema> on 2023-11-15 00:00:00+00:00
[2023-11-22T22:41:37.044+0000] {standard_task_runner.py:57} INFO - Started process 227 to run task
[2023-11-22T22:41:37.098+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'outcomes_dag', 'Initialize_wharehouse_schema', 'scheduled__2023-11-15T00:00:00+00:00', '--job-id', '44', '--raw', '--subdir', 'DAGS_FOLDER/outcomes_dag.py', '--cfg-path', '/tmp/tmpewsanmfq']
[2023-11-22T22:41:37.114+0000] {standard_task_runner.py:85} INFO - Job 44: Subtask Initialize_wharehouse_schema
[2023-11-22T22:41:37.282+0000] {task_command.py:416} INFO - Running <TaskInstance: outcomes_dag.Initialize_wharehouse_schema scheduled__2023-11-15T00:00:00+00:00 [running]> on host 8ac13583809b
[2023-11-22T22:41:37.488+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='outcomes_dag' AIRFLOW_CTX_TASK_ID='Initialize_wharehouse_schema' AIRFLOW_CTX_EXECUTION_DATE='2023-11-15T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-15T00:00:00+00:00'
[2023-11-22T22:41:37.991+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/ETL/load.py", line 16, in execute_sql_script
    client.query(statement)
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/bigquery/client.py", line 3391, in query
    return _job_helpers.query_jobs_insert(
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/bigquery/_job_helpers.py", line 114, in query_jobs_insert
    future = do_query()
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/bigquery/_job_helpers.py", line 91, in do_query
    query_job._begin(retry=retry, timeout=timeout)
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/bigquery/job/query.py", line 1370, in _begin
    super(QueryJob, self)._begin(client=client, retry=retry, timeout=timeout)
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/bigquery/job/base.py", line 693, in _begin
    api_response = client._call_api(
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/bigquery/client.py", line 808, in _call_api
    return call()
  File "/home/airflow/.local/lib/python3.8/site-packages/google/api_core/retry.py", line 366, in retry_wrapped_func
    return retry_target(
  File "/home/airflow/.local/lib/python3.8/site-packages/google/api_core/retry.py", line 204, in retry_target
    return target()
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/_http/__init__.py", line 494, in api_request
    raise exceptions.from_http_response(response)
google.api_core.exceptions.Forbidden: 403 POST https://bigquery.googleapis.com/bigquery/v2/projects/dcsc-warehouse/jobs?prettyPrint=false: Access Denied: Project dcsc-warehouse: User does not have bigquery.jobs.create permission in project dcsc-warehouse.

Location: None
Job ID: 0a189a1b-621c-436f-92bd-0546306c8f08

[2023-11-22T22:41:38.028+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=outcomes_dag, task_id=Initialize_wharehouse_schema, execution_date=20231115T000000, start_date=20231122T224136, end_date=20231122T224138
[2023-11-22T22:41:38.046+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 44 for task Initialize_wharehouse_schema (403 POST https://bigquery.googleapis.com/bigquery/v2/projects/dcsc-warehouse/jobs?prettyPrint=false: Access Denied: Project dcsc-warehouse: User does not have bigquery.jobs.create permission in project dcsc-warehouse.

Location: None
Job ID: 0a189a1b-621c-436f-92bd-0546306c8f08
; 227)
[2023-11-22T22:41:38.102+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-22T22:59:55.346+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: outcomes_dag.Initialize_wharehouse_schema scheduled__2023-11-15T00:00:00+00:00 [queued]>
[2023-11-22T22:59:55.367+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: outcomes_dag.Initialize_wharehouse_schema scheduled__2023-11-15T00:00:00+00:00 [queued]>
[2023-11-22T22:59:55.367+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-11-22T22:59:55.385+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): Initialize_wharehouse_schema> on 2023-11-15 00:00:00+00:00
[2023-11-22T22:59:55.398+0000] {standard_task_runner.py:57} INFO - Started process 188 to run task
[2023-11-22T22:59:55.425+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'outcomes_dag', 'Initialize_wharehouse_schema', 'scheduled__2023-11-15T00:00:00+00:00', '--job-id', '40', '--raw', '--subdir', 'DAGS_FOLDER/outcomes_dag.py', '--cfg-path', '/tmp/tmp6imqdc58']
[2023-11-22T22:59:55.449+0000] {standard_task_runner.py:85} INFO - Job 40: Subtask Initialize_wharehouse_schema
[2023-11-22T22:59:55.592+0000] {task_command.py:416} INFO - Running <TaskInstance: outcomes_dag.Initialize_wharehouse_schema scheduled__2023-11-15T00:00:00+00:00 [running]> on host 4b2f5af281f8
[2023-11-22T22:59:55.787+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='outcomes_dag' AIRFLOW_CTX_TASK_ID='Initialize_wharehouse_schema' AIRFLOW_CTX_EXECUTION_DATE='2023-11-15T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-15T00:00:00+00:00'
[2023-11-22T22:59:57.690+0000] {python.py:194} INFO - Done. Returned value was: None
[2023-11-22T22:59:57.792+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=outcomes_dag, task_id=Initialize_wharehouse_schema, execution_date=20231115T000000, start_date=20231122T225955, end_date=20231122T225957
[2023-11-22T22:59:58.027+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-11-23T00:39:32.479+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: outcomes_dag.Initialize_wharehouse_schema scheduled__2023-11-15T00:00:00+00:00 [queued]>
[2023-11-23T00:39:32.551+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: outcomes_dag.Initialize_wharehouse_schema scheduled__2023-11-15T00:00:00+00:00 [queued]>
[2023-11-23T00:39:32.563+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-11-23T00:39:32.799+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): Initialize_wharehouse_schema> on 2023-11-15 00:00:00+00:00
[2023-11-23T00:39:32.822+0000] {standard_task_runner.py:57} INFO - Started process 197 to run task
[2023-11-23T00:39:32.851+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'outcomes_dag', 'Initialize_wharehouse_schema', 'scheduled__2023-11-15T00:00:00+00:00', '--job-id', '38', '--raw', '--subdir', 'DAGS_FOLDER/outcomes_dag.py', '--cfg-path', '/tmp/tmpcar5kzgc']
[2023-11-23T00:39:32.875+0000] {standard_task_runner.py:85} INFO - Job 38: Subtask Initialize_wharehouse_schema
[2023-11-23T00:39:33.111+0000] {task_command.py:416} INFO - Running <TaskInstance: outcomes_dag.Initialize_wharehouse_schema scheduled__2023-11-15T00:00:00+00:00 [running]> on host 75913536581a
[2023-11-23T00:39:33.419+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='outcomes_dag' AIRFLOW_CTX_TASK_ID='Initialize_wharehouse_schema' AIRFLOW_CTX_EXECUTION_DATE='2023-11-15T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-15T00:00:00+00:00'
[2023-11-23T00:39:35.294+0000] {python.py:194} INFO - Done. Returned value was: None
[2023-11-23T00:39:35.333+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=outcomes_dag, task_id=Initialize_wharehouse_schema, execution_date=20231115T000000, start_date=20231123T003932, end_date=20231123T003935
[2023-11-23T00:39:35.385+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
