[2023-11-22T07:15:11.076+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: outcomes_dag.Insert manual__2023-11-22T07:14:53.499149+00:00 [queued]>
[2023-11-22T07:15:11.082+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: outcomes_dag.Insert manual__2023-11-22T07:14:53.499149+00:00 [queued]>
[2023-11-22T07:15:11.083+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-11-22T07:15:11.094+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): Insert> on 2023-11-22 07:14:53.499149+00:00
[2023-11-22T07:15:11.101+0000] {standard_task_runner.py:57} INFO - Started process 151 to run task
[2023-11-22T07:15:11.124+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'outcomes_dag', 'Insert', 'manual__2023-11-22T07:14:53.499149+00:00', '--job-id', '31', '--raw', '--subdir', 'DAGS_FOLDER/outcomes_dag.py', '--cfg-path', '/tmp/tmpe0o0e3q1']
[2023-11-22T07:15:11.147+0000] {standard_task_runner.py:85} INFO - Job 31: Subtask Insert
[2023-11-22T07:15:11.224+0000] {task_command.py:416} INFO - Running <TaskInstance: outcomes_dag.Insert manual__2023-11-22T07:14:53.499149+00:00 [running]> on host 011245d9ad62
[2023-11-22T07:15:11.323+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='outcomes_dag' AIRFLOW_CTX_TASK_ID='Insert' AIRFLOW_CTX_EXECUTION_DATE='2023-11-22T07:14:53.499149+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-11-22T07:14:53.499149+00:00'
[2023-11-22T07:15:11.342+0000] {logging_mixin.py:154} INFO - Error executing SQL script: (psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "animal_dim_pkey"
DETAIL:  Key ("Animal ID")=(A891289) already exists.

[SQL: --- INSERT DATA INTO DIMENSION TABLES

--- Animal Dimension
INSERT INTO animal_dim ("Animal ID", "Name", "Animal Type", "Breed", "Color", "Sex", "DOB")
SELECT DISTINCT "Animal ID", "Name", "Animal Type", "Breed", "Color", "Sex", "DOB"
FROM outcomes_staging
WHERE "Animal ID" IS NOT NULL;

--- Outcomes Dimension
INSERT INTO outcome_type_dim ("Outcome Type")
SELECT DISTINCT "Outcome"
FROM outcomes_staging
WHERE "Outcome" IS NOT NULL;

--- Reproductive Status Dimension
INSERT INTO reproductive_status_dim ("Reproductive Status")
SELECT DISTINCT "Reproductive Status"
FROM outcomes_staging
WHERE "Reproductive Status" IS NOT NULL;

--- Date Dimension
INSERT INTO date_dim ("Date ID", "Day", "Month", "Year")
SELECT DISTINCT "Date ID", "Day", "Month", "Year"
FROM outcomes_staging
WHERE "Date ID" IS NOT NULL;




--- INSERT DATA INTO FACT TABLE
INSERT INTO outcomes_fct ("Date", "Animal", "Outcome", "Repo Status")
SELECT 
    dd."Date ID",
    ad."Animal ID",
    otd."Outcome ID",
    rsd."Status ID"
FROM outcomes_staging os
JOIN date_dim dd ON os."Date ID" = dd."Date ID"
JOIN animal_dim ad ON os."Animal ID" = ad."Animal ID"
JOIN outcome_type_dim otd ON os."Outcome" = otd."Outcome Type"
JOIN reproductive_status_dim rsd ON os."Reproductive Status" = rsd."Reproductive Status";

]
(Background on this error at: https://sqlalche.me/e/14/gkpj)
[2023-11-22T07:15:11.343+0000] {python.py:194} INFO - Done. Returned value was: None
[2023-11-22T07:15:11.351+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=outcomes_dag, task_id=Insert, execution_date=20231122T071453, start_date=20231122T071511, end_date=20231122T071511
[2023-11-22T07:15:11.380+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-11-22T07:15:11.405+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
