[2023-11-22T05:47:54.392+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: outcomes_dag.Insert scheduled__2023-11-20T00:00:00+00:00 [queued]>
[2023-11-22T05:47:54.399+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: outcomes_dag.Insert scheduled__2023-11-20T00:00:00+00:00 [queued]>
[2023-11-22T05:47:54.399+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-11-22T05:47:54.412+0000] {taskinstance.py:1382} INFO - Executing <Task(PostgresOperator): Insert> on 2023-11-20 00:00:00+00:00
[2023-11-22T05:47:54.418+0000] {standard_task_runner.py:57} INFO - Started process 215 to run task
[2023-11-22T05:47:54.423+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'outcomes_dag', 'Insert', 'scheduled__2023-11-20T00:00:00+00:00', '--job-id', '33', '--raw', '--subdir', 'DAGS_FOLDER/outcomes_dag.py', '--cfg-path', '/tmp/tmpyfxf0l4r']
[2023-11-22T05:47:54.427+0000] {standard_task_runner.py:85} INFO - Job 33: Subtask Insert
[2023-11-22T05:47:54.476+0000] {task_command.py:416} INFO - Running <TaskInstance: outcomes_dag.Insert scheduled__2023-11-20T00:00:00+00:00 [running]> on host 6e2e77b078ed
[2023-11-22T05:47:54.533+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='outcomes_dag' AIRFLOW_CTX_TASK_ID='Insert' AIRFLOW_CTX_EXECUTION_DATE='2023-11-20T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-20T00:00:00+00:00'
[2023-11-22T05:47:54.534+0000] {sql.py:274} INFO - Executing: --- INSERT DATA INTO DIMENSION TABLES

--- Animal Dimension
INSERT INTO animal_dim ("Animal ID", "Name", "Animal Type", "Breed", "Color", "Sex", "DOB")
SELECT DISTINCT "Animal ID", "Name", "Animal Type", "Breed", "Color", "Sex", "DOB"
FROM outcomes_staging
WHERE "Animal ID" IS NOT NULL;

--- Outcomes Dimension
INSERT INTO outcome_type_dim ("Outcome Type")
SELECT DISTINCT "Outcome"
FROM outcomes_staging
WHERE "Outcome" IS NOT NULL;

--- Reproductive Status Dimension
INSERT INTO reproductive_status_dim ("Reproductive Status")
SELECT DISTINCT "Reproductive Status"
FROM outcomes_staging
WHERE "Reproductive Status" IS NOT NULL;

--- Date Dimension
INSERT INTO date_dim ("Date ID", "Day", "Month", "Year")
SELECT DISTINCT "Date ID", "Day", "Month", "Year"
FROM outcomes_staging
WHERE "Date ID" IS NOT NULL;




--- INSERT DATA INTO FACT TABLE
INSERT INTO outcomes_fct ("Date", "Animal", "Outcome", "Repo Status")
SELECT 
    dd."Date ID",
    ad."Animal ID",
    otd."Outcome ID",
    rsd."Status ID"
FROM outcomes_staging os
JOIN date_dim dd ON os."Date ID" = dd."Date ID"
JOIN animal_dim ad ON os."Animal ID" = ad."Animal ID"
JOIN outcome_type_dim otd ON os."Outcome" = otd."Outcome Type"
JOIN reproductive_status_dim rsd ON os."Reproductive Status" = rsd."Reproductive Status";

[2023-11-22T05:47:54.547+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/operators/sql.py", line 275, in execute
    hook = self.get_db_hook()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/operators/sql.py", line 186, in get_db_hook
    return self._hook
  File "/usr/local/lib/python3.8/functools.py", line 967, in __get__
    val = self.func(instance)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/operators/sql.py", line 148, in _hook
    conn = BaseHook.get_connection(conn_id)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/hooks/base.py", line 72, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/connection.py", line 477, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `lab3_postgres_connection` isn't defined
[2023-11-22T05:47:54.550+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=outcomes_dag, task_id=Insert, execution_date=20231120T000000, start_date=20231122T054754, end_date=20231122T054754
[2023-11-22T05:47:54.556+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 33 for task Insert (The conn_id `lab3_postgres_connection` isn't defined; 215)
[2023-11-22T05:47:54.594+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-22T05:47:54.606+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-11-22T06:09:47.509+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: outcomes_dag.Insert scheduled__2023-11-20T00:00:00+00:00 [queued]>
[2023-11-22T06:09:47.526+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: outcomes_dag.Insert scheduled__2023-11-20T00:00:00+00:00 [queued]>
[2023-11-22T06:09:47.526+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-11-22T06:09:47.543+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): Insert> on 2023-11-20 00:00:00+00:00
[2023-11-22T06:09:47.557+0000] {standard_task_runner.py:57} INFO - Started process 138 to run task
[2023-11-22T06:09:47.587+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'outcomes_dag', 'Insert', 'scheduled__2023-11-20T00:00:00+00:00', '--job-id', '26', '--raw', '--subdir', 'DAGS_FOLDER/outcomes_dag.py', '--cfg-path', '/tmp/tmp9asjob74']
[2023-11-22T06:09:47.618+0000] {standard_task_runner.py:85} INFO - Job 26: Subtask Insert
[2023-11-22T06:09:47.791+0000] {task_command.py:416} INFO - Running <TaskInstance: outcomes_dag.Insert scheduled__2023-11-20T00:00:00+00:00 [running]> on host ded66acd9c7f
[2023-11-22T06:09:47.929+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='outcomes_dag' AIRFLOW_CTX_TASK_ID='Insert' AIRFLOW_CTX_EXECUTION_DATE='2023-11-20T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-20T00:00:00+00:00'
[2023-11-22T06:09:48.002+0000] {python.py:194} INFO - Done. Returned value was: None
[2023-11-22T06:09:48.025+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=outcomes_dag, task_id=Insert, execution_date=20231120T000000, start_date=20231122T060947, end_date=20231122T060948
[2023-11-22T06:09:48.043+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-11-22T06:09:48.061+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-11-22T06:19:08.410+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: outcomes_dag.Insert scheduled__2023-11-20T00:00:00+00:00 [queued]>
[2023-11-22T06:19:08.418+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: outcomes_dag.Insert scheduled__2023-11-20T00:00:00+00:00 [queued]>
[2023-11-22T06:19:08.421+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-11-22T06:19:08.433+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): Insert> on 2023-11-20 00:00:00+00:00
[2023-11-22T06:19:08.448+0000] {standard_task_runner.py:57} INFO - Started process 152 to run task
[2023-11-22T06:19:08.472+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'outcomes_dag', 'Insert', 'scheduled__2023-11-20T00:00:00+00:00', '--job-id', '33', '--raw', '--subdir', 'DAGS_FOLDER/outcomes_dag.py', '--cfg-path', '/tmp/tmpis_fmrdc']
[2023-11-22T06:19:08.480+0000] {standard_task_runner.py:85} INFO - Job 33: Subtask Insert
[2023-11-22T06:19:08.547+0000] {task_command.py:416} INFO - Running <TaskInstance: outcomes_dag.Insert scheduled__2023-11-20T00:00:00+00:00 [running]> on host 836b7d8b8a64
[2023-11-22T06:19:08.611+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='outcomes_dag' AIRFLOW_CTX_TASK_ID='Insert' AIRFLOW_CTX_EXECUTION_DATE='2023-11-20T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-20T00:00:00+00:00'
[2023-11-22T06:19:08.645+0000] {python.py:194} INFO - Done. Returned value was: None
[2023-11-22T06:19:08.657+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=outcomes_dag, task_id=Insert, execution_date=20231120T000000, start_date=20231122T061908, end_date=20231122T061908
[2023-11-22T06:19:08.683+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-11-22T06:19:08.696+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-11-22T07:15:11.578+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: outcomes_dag.Insert scheduled__2023-11-20T00:00:00+00:00 [queued]>
[2023-11-22T07:15:11.584+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: outcomes_dag.Insert scheduled__2023-11-20T00:00:00+00:00 [queued]>
[2023-11-22T07:15:11.584+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-11-22T07:15:11.590+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): Insert> on 2023-11-20 00:00:00+00:00
[2023-11-22T07:15:11.594+0000] {standard_task_runner.py:57} INFO - Started process 154 to run task
[2023-11-22T07:15:11.597+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'outcomes_dag', 'Insert', 'scheduled__2023-11-20T00:00:00+00:00', '--job-id', '34', '--raw', '--subdir', 'DAGS_FOLDER/outcomes_dag.py', '--cfg-path', '/tmp/tmpisov8h0w']
[2023-11-22T07:15:11.599+0000] {standard_task_runner.py:85} INFO - Job 34: Subtask Insert
[2023-11-22T07:15:11.632+0000] {task_command.py:416} INFO - Running <TaskInstance: outcomes_dag.Insert scheduled__2023-11-20T00:00:00+00:00 [running]> on host 011245d9ad62
[2023-11-22T07:15:11.683+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='outcomes_dag' AIRFLOW_CTX_TASK_ID='Insert' AIRFLOW_CTX_EXECUTION_DATE='2023-11-20T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-20T00:00:00+00:00'
[2023-11-22T07:15:11.693+0000] {logging_mixin.py:154} INFO - Error executing SQL script: (psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "animal_dim_pkey"
DETAIL:  Key ("Animal ID")=(A891289) already exists.

[SQL: --- INSERT DATA INTO DIMENSION TABLES

--- Animal Dimension
INSERT INTO animal_dim ("Animal ID", "Name", "Animal Type", "Breed", "Color", "Sex", "DOB")
SELECT DISTINCT "Animal ID", "Name", "Animal Type", "Breed", "Color", "Sex", "DOB"
FROM outcomes_staging
WHERE "Animal ID" IS NOT NULL;

--- Outcomes Dimension
INSERT INTO outcome_type_dim ("Outcome Type")
SELECT DISTINCT "Outcome"
FROM outcomes_staging
WHERE "Outcome" IS NOT NULL;

--- Reproductive Status Dimension
INSERT INTO reproductive_status_dim ("Reproductive Status")
SELECT DISTINCT "Reproductive Status"
FROM outcomes_staging
WHERE "Reproductive Status" IS NOT NULL;

--- Date Dimension
INSERT INTO date_dim ("Date ID", "Day", "Month", "Year")
SELECT DISTINCT "Date ID", "Day", "Month", "Year"
FROM outcomes_staging
WHERE "Date ID" IS NOT NULL;




--- INSERT DATA INTO FACT TABLE
INSERT INTO outcomes_fct ("Date", "Animal", "Outcome", "Repo Status")
SELECT 
    dd."Date ID",
    ad."Animal ID",
    otd."Outcome ID",
    rsd."Status ID"
FROM outcomes_staging os
JOIN date_dim dd ON os."Date ID" = dd."Date ID"
JOIN animal_dim ad ON os."Animal ID" = ad."Animal ID"
JOIN outcome_type_dim otd ON os."Outcome" = otd."Outcome Type"
JOIN reproductive_status_dim rsd ON os."Reproductive Status" = rsd."Reproductive Status";

]
(Background on this error at: https://sqlalche.me/e/14/gkpj)
[2023-11-22T07:15:11.693+0000] {python.py:194} INFO - Done. Returned value was: None
[2023-11-22T07:15:11.700+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=outcomes_dag, task_id=Insert, execution_date=20231120T000000, start_date=20231122T071511, end_date=20231122T071511
[2023-11-22T07:15:11.730+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-11-22T07:15:11.741+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-11-22T07:54:45.561+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: outcomes_dag.Insert scheduled__2023-11-20T00:00:00+00:00 [queued]>
[2023-11-22T07:54:45.571+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: outcomes_dag.Insert scheduled__2023-11-20T00:00:00+00:00 [queued]>
[2023-11-22T07:54:45.571+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-11-22T07:54:45.579+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): Insert> on 2023-11-20 00:00:00+00:00
[2023-11-22T07:54:45.587+0000] {standard_task_runner.py:57} INFO - Started process 485 to run task
[2023-11-22T07:54:45.592+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'outcomes_dag', 'Insert', 'scheduled__2023-11-20T00:00:00+00:00', '--job-id', '83', '--raw', '--subdir', 'DAGS_FOLDER/outcomes_dag.py', '--cfg-path', '/tmp/tmpr3_x5vc6']
[2023-11-22T07:54:45.597+0000] {standard_task_runner.py:85} INFO - Job 83: Subtask Insert
[2023-11-22T07:54:45.651+0000] {task_command.py:416} INFO - Running <TaskInstance: outcomes_dag.Insert scheduled__2023-11-20T00:00:00+00:00 [running]> on host 6318e996d951
[2023-11-22T07:54:45.715+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='outcomes_dag' AIRFLOW_CTX_TASK_ID='Insert' AIRFLOW_CTX_EXECUTION_DATE='2023-11-20T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-20T00:00:00+00:00'
[2023-11-22T07:54:45.748+0000] {logging_mixin.py:154} INFO - Error executing SQL script: (psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "animal_dim_pkey"
DETAIL:  Key ("Animal ID")=(A891289) already exists.

[SQL: --- INSERT DATA INTO DIMENSION TABLES

--- Animal Dimension
INSERT INTO animal_dim ("Animal ID", "Name", "Animal Type", "Breed", "Color", "Sex", "DOB")
SELECT DISTINCT "Animal ID", "Name", "Animal Type", "Breed", "Color", "Sex", "DOB"
FROM outcomes_staging
WHERE "Animal ID" IS NOT NULL;

--- Outcomes Dimension
INSERT INTO outcome_type_dim ("Outcome Type")
SELECT DISTINCT "Outcome"
FROM outcomes_staging
WHERE "Outcome" IS NOT NULL;

--- Reproductive Status Dimension
INSERT INTO reproductive_status_dim ("Reproductive Status")
SELECT DISTINCT "Reproductive Status"
FROM outcomes_staging
WHERE "Reproductive Status" IS NOT NULL;

--- Date Dimension
INSERT INTO date_dim ("Date ID", "Day", "Month", "Year")
SELECT DISTINCT "Date ID", "Day", "Month", "Year"
FROM outcomes_staging
WHERE "Date ID" IS NOT NULL;




--- INSERT DATA INTO FACT TABLE
INSERT INTO outcomes_fct ("Date", "Animal", "Outcome", "Repo Status")
SELECT 
    dd."Date ID",
    ad."Animal ID",
    otd."Outcome ID",
    rsd."Status ID"
FROM outcomes_staging os
JOIN date_dim dd ON os."Date ID" = dd."Date ID"
JOIN animal_dim ad ON os."Animal ID" = ad."Animal ID"
JOIN outcome_type_dim otd ON os."Outcome" = otd."Outcome Type"
JOIN reproductive_status_dim rsd ON os."Reproductive Status" = rsd."Reproductive Status";

]
(Background on this error at: https://sqlalche.me/e/14/gkpj)
[2023-11-22T07:54:45.748+0000] {python.py:194} INFO - Done. Returned value was: None
[2023-11-22T07:54:45.758+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=outcomes_dag, task_id=Insert, execution_date=20231120T000000, start_date=20231122T075445, end_date=20231122T075445
[2023-11-22T07:54:45.806+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-11-22T07:54:45.825+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-11-23T01:50:09.105+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: outcomes_dag.Insert scheduled__2023-11-20T00:00:00+00:00 [queued]>
[2023-11-23T01:50:09.116+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: outcomes_dag.Insert scheduled__2023-11-20T00:00:00+00:00 [queued]>
[2023-11-23T01:50:09.118+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-11-23T01:50:09.145+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): Insert> on 2023-11-20 00:00:00+00:00
[2023-11-23T01:50:09.152+0000] {standard_task_runner.py:57} INFO - Started process 330 to run task
[2023-11-23T01:50:09.156+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'outcomes_dag', 'Insert', 'scheduled__2023-11-20T00:00:00+00:00', '--job-id', '84', '--raw', '--subdir', 'DAGS_FOLDER/outcomes_dag.py', '--cfg-path', '/tmp/tmphm9c22gc']
[2023-11-23T01:50:09.161+0000] {standard_task_runner.py:85} INFO - Job 84: Subtask Insert
[2023-11-23T01:50:09.262+0000] {task_command.py:416} INFO - Running <TaskInstance: outcomes_dag.Insert scheduled__2023-11-20T00:00:00+00:00 [running]> on host d15d3caa5b00
[2023-11-23T01:50:09.348+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='outcomes_dag' AIRFLOW_CTX_TASK_ID='Insert' AIRFLOW_CTX_EXECUTION_DATE='2023-11-20T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-20T00:00:00+00:00'
[2023-11-23T01:50:09.363+0000] {logging_mixin.py:154} INFO - Error executing SQL script: (psycopg2.errors.SyntaxError) syntax error at or near "`"
LINE 4: INSERT INTO animal_dim (`Animal ID`, `Name`, `Animal Type`, ...
                                ^

[SQL: -- INSERT DATA INTO DIMENSION TABLES

-- Animal Dimension
INSERT INTO animal_dim (`Animal ID`, `Name`, `Animal Type`, `Breed`, `Color`, `Sex`, `DOB`)
SELECT DISTINCT `Animal ID`, `Name`, `Animal Type`, `Breed`, `Color`, `Sex`, `DOB`
FROM outcomes_staging
WHERE `Animal ID` IS NOT NULL;

-- Outcomes Dimension
INSERT INTO outcome_type_dim (`Outcome Type`)
SELECT DISTINCT `Outcome`
FROM outcomes_staging
WHERE `Outcome` IS NOT NULL;

-- Reproductive Status Dimension
INSERT INTO reproductive_status_dim (`Reproductive Status`)
SELECT DISTINCT `Reproductive Status`
FROM outcomes_staging
WHERE `Reproductive Status` IS NOT NULL;

-- Date Dimension
INSERT INTO date_dim (`Date ID`, `Day`, `Month`, `Year`)
SELECT DISTINCT `Date ID`, `Day`, `Month`, `Year`
FROM outcomes_staging
WHERE `Date ID` IS NOT NULL;

-- INSERT DATA INTO FACT TABLE
INSERT INTO outcomes_fct (`Date`, `Animal`, `Outcome`, `Repo Status`)
SELECT 
    dd.`Date ID`,
    ad.`Animal ID`,
    otd.`Outcome ID`,
    rsd.`Status ID`
FROM outcomes_staging os
JOIN date_dim dd ON os.`Date ID` = dd.`Date ID`
JOIN animal_dim ad ON os.`Animal ID` = ad.`Animal ID`
JOIN outcome_type_dim otd ON os.`Outcome` = otd.`Outcome Type`
JOIN reproductive_status_dim rsd ON os.`Reproductive Status` = rsd.`Reproductive Status`;
]
(Background on this error at: https://sqlalche.me/e/14/f405)
[2023-11-23T01:50:09.363+0000] {python.py:194} INFO - Done. Returned value was: None
[2023-11-23T01:50:09.385+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=outcomes_dag, task_id=Insert, execution_date=20231120T000000, start_date=20231123T015009, end_date=20231123T015009
[2023-11-23T01:50:09.420+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-11-23T01:50:09.434+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-11-23T01:58:46.803+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: outcomes_dag.Insert scheduled__2023-11-20T00:00:00+00:00 [queued]>
[2023-11-23T01:58:46.811+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: outcomes_dag.Insert scheduled__2023-11-20T00:00:00+00:00 [queued]>
[2023-11-23T01:58:46.811+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-11-23T01:58:46.820+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): Insert> on 2023-11-20 00:00:00+00:00
[2023-11-23T01:58:46.834+0000] {standard_task_runner.py:57} INFO - Started process 140 to run task
[2023-11-23T01:58:46.855+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'outcomes_dag', 'Insert', 'scheduled__2023-11-20T00:00:00+00:00', '--job-id', '29', '--raw', '--subdir', 'DAGS_FOLDER/outcomes_dag.py', '--cfg-path', '/tmp/tmpkezud5a7']
[2023-11-23T01:58:46.865+0000] {standard_task_runner.py:85} INFO - Job 29: Subtask Insert
[2023-11-23T01:58:46.953+0000] {task_command.py:416} INFO - Running <TaskInstance: outcomes_dag.Insert scheduled__2023-11-20T00:00:00+00:00 [running]> on host 3cdc572bc068
[2023-11-23T01:58:47.041+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='outcomes_dag' AIRFLOW_CTX_TASK_ID='Insert' AIRFLOW_CTX_EXECUTION_DATE='2023-11-20T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-20T00:00:00+00:00'
[2023-11-23T01:58:47.074+0000] {logging_mixin.py:154} INFO - Error executing SQL script: (psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "animal_dim_pkey"
DETAIL:  Key ("Animal ID")=(A887504) already exists.

[SQL: --- INSERT DATA INTO DIMENSION TABLES

--- Animal Dimension
INSERT INTO animal_dim ("Animal ID", "Name", "Animal Type", "Breed", "Color", "Sex", "DOB")
SELECT DISTINCT "Animal ID", "Name", "Animal Type", "Breed", "Color", "Sex", "DOB"
FROM outcomes_staging
WHERE "Animal ID" IS NOT NULL;

--- Outcomes Dimension
INSERT INTO outcome_type_dim ("Outcome Type")
SELECT DISTINCT "Outcome"
FROM outcomes_staging
WHERE "Outcome" IS NOT NULL;

--- Reproductive Status Dimension
INSERT INTO reproductive_status_dim ("Reproductive Status")
SELECT DISTINCT "Reproductive Status"
FROM outcomes_staging
WHERE "Reproductive Status" IS NOT NULL;

--- Date Dimension
INSERT INTO date_dim ("Date ID", "Day", "Month", "Year")
SELECT DISTINCT "Date ID", "Day", "Month", "Year"
FROM outcomes_staging
WHERE "Date ID" IS NOT NULL;




--- INSERT DATA INTO FACT TABLE
INSERT INTO outcomes_fct ("Date", "Animal", "Outcome", "Repo Status")
SELECT 
    dd."Date ID",
    ad."Animal ID",
    otd."Outcome ID",
    rsd."Status ID"
FROM outcomes_staging os
JOIN date_dim dd ON os."Date ID" = dd."Date ID"
JOIN animal_dim ad ON os."Animal ID" = ad."Animal ID"
JOIN outcome_type_dim otd ON os."Outcome" = otd."Outcome Type"
JOIN reproductive_status_dim rsd ON os."Reproductive Status" = rsd."Reproductive Status";

]
(Background on this error at: https://sqlalche.me/e/14/gkpj)
[2023-11-23T01:58:47.074+0000] {python.py:194} INFO - Done. Returned value was: None
[2023-11-23T01:58:47.098+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=outcomes_dag, task_id=Insert, execution_date=20231120T000000, start_date=20231123T015846, end_date=20231123T015847
[2023-11-23T01:58:47.140+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-11-23T01:58:47.158+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-11-23T02:59:47.092+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: outcomes_dag.Insert scheduled__2023-11-20T00:00:00+00:00 [queued]>
[2023-11-23T02:59:47.102+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: outcomes_dag.Insert scheduled__2023-11-20T00:00:00+00:00 [queued]>
[2023-11-23T02:59:47.103+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-11-23T02:59:47.381+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): Insert> on 2023-11-20 00:00:00+00:00
[2023-11-23T02:59:47.389+0000] {standard_task_runner.py:57} INFO - Started process 186 to run task
[2023-11-23T02:59:47.397+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'outcomes_dag', 'Insert', 'scheduled__2023-11-20T00:00:00+00:00', '--job-id', '27', '--raw', '--subdir', 'DAGS_FOLDER/outcomes_dag.py', '--cfg-path', '/tmp/tmp9ctizcgp']
[2023-11-23T02:59:47.399+0000] {standard_task_runner.py:85} INFO - Job 27: Subtask Insert
[2023-11-23T02:59:47.467+0000] {task_command.py:416} INFO - Running <TaskInstance: outcomes_dag.Insert scheduled__2023-11-20T00:00:00+00:00 [running]> on host 1268bd8e5db0
[2023-11-23T02:59:47.558+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='outcomes_dag' AIRFLOW_CTX_TASK_ID='Insert' AIRFLOW_CTX_EXECUTION_DATE='2023-11-20T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-20T00:00:00+00:00'
[2023-11-23T02:59:47.559+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
TypeError: execute_sql_script() missing 1 required positional argument: 'engine'
[2023-11-23T02:59:47.566+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=outcomes_dag, task_id=Insert, execution_date=20231120T000000, start_date=20231123T025947, end_date=20231123T025947
[2023-11-23T02:59:47.572+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 27 for task Insert (execute_sql_script() missing 1 required positional argument: 'engine'; 186)
[2023-11-23T02:59:47.605+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-23T02:59:47.619+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-11-23T03:42:23.959+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: outcomes_dag.Insert scheduled__2023-11-20T00:00:00+00:00 [queued]>
[2023-11-23T03:42:24.025+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: outcomes_dag.Insert scheduled__2023-11-20T00:00:00+00:00 [queued]>
[2023-11-23T03:42:24.033+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-11-23T03:42:24.134+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): Insert> on 2023-11-20 00:00:00+00:00
[2023-11-23T03:42:24.178+0000] {standard_task_runner.py:57} INFO - Started process 613 to run task
[2023-11-23T03:42:24.186+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'outcomes_dag', 'Insert', 'scheduled__2023-11-20T00:00:00+00:00', '--job-id', '179', '--raw', '--subdir', 'DAGS_FOLDER/outcomes_dag.py', '--cfg-path', '/tmp/tmpl_fvdktp']
[2023-11-23T03:42:24.197+0000] {standard_task_runner.py:85} INFO - Job 179: Subtask Insert
[2023-11-23T03:42:24.864+0000] {task_command.py:416} INFO - Running <TaskInstance: outcomes_dag.Insert scheduled__2023-11-20T00:00:00+00:00 [running]> on host e647c96745b0
[2023-11-23T03:42:25.439+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='outcomes_dag' AIRFLOW_CTX_TASK_ID='Insert' AIRFLOW_CTX_EXECUTION_DATE='2023-11-20T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-20T00:00:00+00:00'
[2023-11-23T03:42:25.524+0000] {logging_mixin.py:154} INFO - Error executing SQL script: (psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "animal_dim_pkey"
DETAIL:  Key ("Animal ID")=(A891289) already exists.

[SQL: --- INSERT DATA INTO DIMENSION TABLES

--- Animal Dimension
INSERT INTO animal_dim ("Animal ID", "Name", "Animal Type", "Breed", "Color", "Sex", "DOB")
SELECT DISTINCT "Animal ID", "Name", "Animal Type", "Breed", "Color", "Sex", "DOB"
FROM outcomes_staging
WHERE "Animal ID" IS NOT NULL;

--- Outcomes Dimension
INSERT INTO outcome_type_dim ("Outcome Type")
SELECT DISTINCT "Outcome"
FROM outcomes_staging
WHERE "Outcome" IS NOT NULL;

--- Reproductive Status Dimension
INSERT INTO reproductive_status_dim ("Reproductive Status")
SELECT DISTINCT "Reproductive Status"
FROM outcomes_staging
WHERE "Reproductive Status" IS NOT NULL;

--- Date Dimension
INSERT INTO date_dim ("Date ID", "Day", "Month", "Year")
SELECT DISTINCT "Date ID", "Day", "Month", "Year"
FROM outcomes_staging
WHERE "Date ID" IS NOT NULL;




--- INSERT DATA INTO FACT TABLE
INSERT INTO outcomes_fct ("Date", "Animal", "Outcome", "Repo Status")
SELECT 
    dd."Date ID",
    ad."Animal ID",
    otd."Outcome ID",
    rsd."Status ID"
FROM outcomes_staging os
JOIN date_dim dd ON os."Date ID" = dd."Date ID"
JOIN animal_dim ad ON os."Animal ID" = ad."Animal ID"
JOIN outcome_type_dim otd ON os."Outcome" = otd."Outcome Type"
JOIN reproductive_status_dim rsd ON os."Reproductive Status" = rsd."Reproductive Status";

]
(Background on this error at: https://sqlalche.me/e/14/gkpj)
[2023-11-23T03:42:25.525+0000] {python.py:194} INFO - Done. Returned value was: None
[2023-11-23T03:42:25.559+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=outcomes_dag, task_id=Insert, execution_date=20231120T000000, start_date=20231123T034223, end_date=20231123T034225
[2023-11-23T03:42:25.691+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
