[2023-11-22T22:41:35.542+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: outcomes_dag.Initialize_wharehouse_schema scheduled__2023-11-02T00:00:00+00:00 [queued]>
[2023-11-22T22:41:35.578+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: outcomes_dag.Initialize_wharehouse_schema scheduled__2023-11-02T00:00:00+00:00 [queued]>
[2023-11-22T22:41:35.581+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-11-22T22:41:35.656+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): Initialize_wharehouse_schema> on 2023-11-02 00:00:00+00:00
[2023-11-22T22:41:35.842+0000] {standard_task_runner.py:57} INFO - Started process 221 to run task
[2023-11-22T22:41:35.867+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'outcomes_dag', 'Initialize_wharehouse_schema', 'scheduled__2023-11-02T00:00:00+00:00', '--job-id', '38', '--raw', '--subdir', 'DAGS_FOLDER/outcomes_dag.py', '--cfg-path', '/tmp/tmp0_ewt4v6']
[2023-11-22T22:41:35.904+0000] {standard_task_runner.py:85} INFO - Job 38: Subtask Initialize_wharehouse_schema
[2023-11-22T22:41:36.185+0000] {task_command.py:416} INFO - Running <TaskInstance: outcomes_dag.Initialize_wharehouse_schema scheduled__2023-11-02T00:00:00+00:00 [running]> on host 8ac13583809b
[2023-11-22T22:41:36.465+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='outcomes_dag' AIRFLOW_CTX_TASK_ID='Initialize_wharehouse_schema' AIRFLOW_CTX_EXECUTION_DATE='2023-11-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-02T00:00:00+00:00'
[2023-11-22T22:41:36.923+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/ETL/load.py", line 16, in execute_sql_script
    client.query(statement)
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/bigquery/client.py", line 3391, in query
    return _job_helpers.query_jobs_insert(
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/bigquery/_job_helpers.py", line 114, in query_jobs_insert
    future = do_query()
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/bigquery/_job_helpers.py", line 91, in do_query
    query_job._begin(retry=retry, timeout=timeout)
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/bigquery/job/query.py", line 1370, in _begin
    super(QueryJob, self)._begin(client=client, retry=retry, timeout=timeout)
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/bigquery/job/base.py", line 693, in _begin
    api_response = client._call_api(
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/bigquery/client.py", line 808, in _call_api
    return call()
  File "/home/airflow/.local/lib/python3.8/site-packages/google/api_core/retry.py", line 366, in retry_wrapped_func
    return retry_target(
  File "/home/airflow/.local/lib/python3.8/site-packages/google/api_core/retry.py", line 204, in retry_target
    return target()
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/_http/__init__.py", line 494, in api_request
    raise exceptions.from_http_response(response)
google.api_core.exceptions.Forbidden: 403 POST https://bigquery.googleapis.com/bigquery/v2/projects/dcsc-warehouse/jobs?prettyPrint=false: Access Denied: Project dcsc-warehouse: User does not have bigquery.jobs.create permission in project dcsc-warehouse.

Location: None
Job ID: 2a79d004-eba8-4cbc-b06f-de59f4e24e37

[2023-11-22T22:41:37.008+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=outcomes_dag, task_id=Initialize_wharehouse_schema, execution_date=20231102T000000, start_date=20231122T224135, end_date=20231122T224137
[2023-11-22T22:41:37.065+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 38 for task Initialize_wharehouse_schema (403 POST https://bigquery.googleapis.com/bigquery/v2/projects/dcsc-warehouse/jobs?prettyPrint=false: Access Denied: Project dcsc-warehouse: User does not have bigquery.jobs.create permission in project dcsc-warehouse.

Location: None
Job ID: 2a79d004-eba8-4cbc-b06f-de59f4e24e37
; 221)
[2023-11-22T22:41:37.188+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-22T22:59:55.238+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: outcomes_dag.Initialize_wharehouse_schema scheduled__2023-11-02T00:00:00+00:00 [queued]>
[2023-11-22T22:59:55.285+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: outcomes_dag.Initialize_wharehouse_schema scheduled__2023-11-02T00:00:00+00:00 [queued]>
[2023-11-22T22:59:55.298+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-11-22T22:59:55.358+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): Initialize_wharehouse_schema> on 2023-11-02 00:00:00+00:00
[2023-11-22T22:59:55.391+0000] {standard_task_runner.py:57} INFO - Started process 187 to run task
[2023-11-22T22:59:55.413+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'outcomes_dag', 'Initialize_wharehouse_schema', 'scheduled__2023-11-02T00:00:00+00:00', '--job-id', '39', '--raw', '--subdir', 'DAGS_FOLDER/outcomes_dag.py', '--cfg-path', '/tmp/tmpcr3yunsy']
[2023-11-22T22:59:55.419+0000] {standard_task_runner.py:85} INFO - Job 39: Subtask Initialize_wharehouse_schema
[2023-11-22T22:59:55.604+0000] {task_command.py:416} INFO - Running <TaskInstance: outcomes_dag.Initialize_wharehouse_schema scheduled__2023-11-02T00:00:00+00:00 [running]> on host 4b2f5af281f8
[2023-11-22T22:59:55.845+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='outcomes_dag' AIRFLOW_CTX_TASK_ID='Initialize_wharehouse_schema' AIRFLOW_CTX_EXECUTION_DATE='2023-11-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-02T00:00:00+00:00'
[2023-11-22T22:59:57.684+0000] {python.py:194} INFO - Done. Returned value was: None
[2023-11-22T22:59:57.833+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=outcomes_dag, task_id=Initialize_wharehouse_schema, execution_date=20231102T000000, start_date=20231122T225955, end_date=20231122T225957
[2023-11-22T22:59:58.046+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-11-23T00:39:33.026+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: outcomes_dag.Initialize_wharehouse_schema scheduled__2023-11-02T00:00:00+00:00 [queued]>
[2023-11-23T00:39:33.055+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: outcomes_dag.Initialize_wharehouse_schema scheduled__2023-11-02T00:00:00+00:00 [queued]>
[2023-11-23T00:39:33.059+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-11-23T00:39:33.104+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): Initialize_wharehouse_schema> on 2023-11-02 00:00:00+00:00
[2023-11-23T00:39:33.117+0000] {standard_task_runner.py:57} INFO - Started process 201 to run task
[2023-11-23T00:39:33.192+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'outcomes_dag', 'Initialize_wharehouse_schema', 'scheduled__2023-11-02T00:00:00+00:00', '--job-id', '42', '--raw', '--subdir', 'DAGS_FOLDER/outcomes_dag.py', '--cfg-path', '/tmp/tmpye4o1f0a']
[2023-11-23T00:39:33.214+0000] {standard_task_runner.py:85} INFO - Job 42: Subtask Initialize_wharehouse_schema
[2023-11-23T00:39:33.435+0000] {task_command.py:416} INFO - Running <TaskInstance: outcomes_dag.Initialize_wharehouse_schema scheduled__2023-11-02T00:00:00+00:00 [running]> on host 75913536581a
[2023-11-23T00:39:33.645+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='outcomes_dag' AIRFLOW_CTX_TASK_ID='Initialize_wharehouse_schema' AIRFLOW_CTX_EXECUTION_DATE='2023-11-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-02T00:00:00+00:00'
[2023-11-23T00:39:35.288+0000] {python.py:194} INFO - Done. Returned value was: None
[2023-11-23T00:39:35.325+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=outcomes_dag, task_id=Initialize_wharehouse_schema, execution_date=20231102T000000, start_date=20231123T003933, end_date=20231123T003935
[2023-11-23T00:39:35.371+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
